name: actor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  #Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  # provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  # easy way to add shimmer effect
  shimmer: ^3.0.0
  #state mangment
  flutter_bloc: ^8.1.6
  #depency Injecgen
  get_it: ^8.0.0
  #Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_annotation: ^4.8.1
  #error Handling
  either_dart: ^1.0.0
  #Localization
  easy_localization: ^3.0.7
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  # Flutter library to load and cache network images.
  cached_network_image: ^3.3.1
  
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=8.0.0 <10.0.0' 
  build_runner: ^2.3.3
  json_serializable: ^6.8.0 

flutter:
  uses-material-design: true
  assets:
    - data.env
    - assets/translations/